server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/brb-srtp?serverTimezone=GMT%2b8
    username: root
    password: gaoyiren011218
  http:
    multipart:
      location:/data/upload_tmp
#  security:
#    user:
#      name: admin
#      password: 123123

#  servlet:
#    multipart:
#      enabled: true
#      #???????
#      max-file-size: 20MB
#      #??????
#      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml #????mybatis?xml??

#  configuration:configuration
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

files:
  upload:
    path: D:/SRTP/carbon-srtp/Java/data/
#    path: home/files


#jasypt:
#  encryptor:
#    password: gaoyiren011218